import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  fr: {
    'Email': 'E-mail', 'GitHub details coming soon': 'Informations GitHub bientôt disponibles', 'Academic project': 'Projet académique', 'Data and validation': 'Données et validation', 'application.': 'application.',
    'Your message could not be sent. Please try again or use the email link.': 'Votre message n’a pas pu être envoyé. Veuillez réessayer ou utiliser le lien e-mail.', 'Your message could not be sent. Please try again later.': 'Votre message n’a pas pu être envoyé. Veuillez réessayer plus tard.',
    'The React client sends REST requests through the Spring Cloud API Gateway to the Spring Boot services. Spring Data JPA persists catalog, customer, order, and quote data in MySQL.': 'Le client React envoie des requêtes REST via la passerelle API Spring Cloud vers les services Spring Boot. Spring Data JPA enregistre le catalogue, les clients, les commandes et les devis dans MySQL.',
    'Currently continuing my studies in an evening program.': 'Je poursuis actuellement mes études dans un programme du soir.',
    'Mohamed Yahya Sellami | Full-Stack, IoT & Software Testing': 'Mohamed Yahya Sellami | Développement Full-Stack, IoT et tests logiciels',
    'Home': 'Accueil', 'Experience': 'Expérience', 'Skills': 'Compétences', 'Projects': 'Projets', 'Education': 'Formation', 'Contact': 'Contact',
    'Main navigation': 'Navigation principale', 'Skip to content': 'Passer au contenu', 'Download CV': 'Télécharger le CV', 'Switch to light mode': 'Activer le mode clair', 'Switch to dark mode': 'Activer le mode sombre',
    'Language': 'Langue', 'Hi, I’m': 'Bonjour, je suis', 'Open to full-time opportunities': 'Ouvert aux opportunités à temps plein', 'Junior Full-Stack & IoT Developer | Software Testing': 'Développeur junior full-stack et IoT | Tests logiciels',
    'Full-stack development, embedded IoT, and software testing.': 'Développement full-stack, IoT embarqué et tests logiciels.', 'View projects': 'Voir les projets', 'ABOUT ME': 'À PROPOS', 'ENGINEERING MINDSET': 'ESPRIT D’INGÉNIEUR',
    'I build full-stack and IoT systems that connect software with the physical world.': 'Je développe des systèmes full-stack et IoT qui relient les logiciels au monde physique.',
    'Computer Science and Information Systems graduate with hands-on experience in full-stack development, IoT systems, and software testing. Experienced in API, integration, and system testing across backend, web, mobile, and embedded environments. Skilled in Spring Boot, PostgreSQL, React, Flutter, C/C++, REST APIs, MQTT, and hardware–software integration. Strong understanding of end-to-end system behavior with a focus on reliability, software quality, and problem solving.': 'Diplômé en informatique et systèmes d’information, j’ai une expérience pratique en développement full-stack, systèmes IoT et tests logiciels. J’ai testé des API et réalisé des tests d’intégration et système sur des environnements backend, web, mobile et embarqués. Je maîtrise notamment Spring Boot, PostgreSQL, React, Flutter, C/C++, les API REST, MQTT et l’intégration matériel-logiciel. Je m’intéresse à la fiabilité, à la qualité logicielle et à la résolution de problèmes.',
    'Embedded systems': 'Systèmes embarqués', 'Full-stack software': 'Logiciels full-stack', 'Reliable delivery': 'Livraison fiable', 'Available for daytime work.': 'Disponible pour travailler en journée.', 'My engineering classes are in the evening.': 'Mes cours d’ingénieur ont lieu le soir.',
    'EXPERIENCE': 'EXPÉRIENCE', 'Engineering in practice.': 'L’ingénierie en pratique.', 'Hands-on work across software, connected devices, and the places where they meet.': 'Expérience pratique en développement logiciel, objets connectés et intégration des deux.',
    'Professional internships': 'Stages professionnels', 'Software, IoT, and technical support roles.': 'Missions en développement logiciel, IoT et support technique.', 'Leadership & community': 'Leadership et engagement associatif', 'IEEE RAS IIT SBC and Scouts.': 'IEEE RAS IIT SBC et Scouts.', 'ROLES': 'POSTES', 'Professional internship': 'Stage professionnel', 'Associative experience': 'Engagement associatif', 'Explore the project': 'Découvrir le projet',
    'Full-Stack & IoT Developer Intern': 'Stagiaire développeur full-stack et IoT', 'Contributed across the BlueBox smart irrigation platform, building backend, web, and mobile features alongside ESP32-S3 firmware and controller integration.': 'Contribution à la plateforme d’irrigation intelligente BlueBox : développement backend, web et mobile, firmware ESP32-S3 et intégration du contrôleur.',
    'Developed Java and Spring Boot REST APIs with PostgreSQL for device management, irrigation programs, logs, and live status; used Docker for the backend and database development environment.': 'Développement d’API REST avec Java, Spring Boot et PostgreSQL pour gérer les appareils, les programmes d’irrigation, les journaux et les états en direct. Utilisation de Docker pour l’environnement backend et base de données.',
    'Built React dashboard and Flutter mobile features for monitoring, configuration, reporting, controller onboarding, irrigation scheduling, and remote valve control.': 'Développement de fonctionnalités avec React et Flutter pour la supervision, la configuration, les rapports, l’installation des contrôleurs, la programmation de l’irrigation et le pilotage à distance des vannes.',
    'Integrated REST/JSON and MQTT data exchange between applications, backend services, and ESP32-S3 controllers, and added Firebase Cloud Messaging alerts.': 'Intégration des échanges REST/JSON et MQTT entre les applications, les services backend et les contrôleurs ESP32-S3, ainsi que des alertes Firebase Cloud Messaging.',
    'Developed C/C++ firmware and the TFT interface for irrigation control, Wi-Fi onboarding, valve and pump states, sensor and pressure monitoring, and HTTPS OTA updates.': 'Développement du firmware C/C++ et de l’interface TFT pour le contrôle de l’irrigation, la connexion Wi-Fi, l’état des vannes et de la pompe, la surveillance des capteurs et de la pression, et les mises à jour OTA par HTTPS.',
    'Performed API, integration, and system testing across web, mobile, backend, and IoT components; investigated defects and verified fixes to improve reliability.': 'Réalisation de tests API, d’intégration et système sur les composants web, mobile, backend et IoT ; analyse des anomalies et vérification des correctifs pour améliorer la fiabilité.',
    'Used Git for version control and Jira to track tasks, blockers, and dependencies; contributed to Scrum planning, daily Scrum, reviews, retrospectives, and backlog refinement across the team.': 'Utilisation de Git et Jira pour le suivi des tâches, blocages et dépendances ; participation à la planification Scrum, aux réunions quotidiennes, revues, rétrospectives et affinements du backlog.',
    'Full-Stack Development Intern': 'Stagiaire en développement full-stack', 'Developed a commercial management web application for SECOME, connecting a customer storefront with an administration portal and backend services.': 'Développement d’une application web de gestion commerciale pour SECOME, reliant une boutique client à un portail d’administration et à des services backend.',
    'Built customer flows for browsing products, managing a cart, placing orders, and retrieving downloadable PDF quotes.': 'Création des parcours clients pour consulter les produits, gérer un panier, passer des commandes et récupérer des devis PDF.',
    'Implemented Spring Boot microservices with Spring Cloud routing, Spring Data JPA, and MySQL; developed the interface with React and Axios.': 'Mise en place de microservices Spring Boot avec routage Spring Cloud, Spring Data JPA et MySQL ; développement de l’interface avec React et Axios.',
    'Created protected administration workflows for the product catalog, customers, orders, and quote review and approval.': 'Création d’espaces d’administration sécurisés pour gérer le catalogue, les clients, les commandes et la validation des devis.',
    'Tested REST endpoints with Postman and checked integration between the frontend and backend; used Kanban and UML to organize and model the work.': 'Test des API REST avec Postman et vérification de l’intégration frontend/backend ; organisation du travail avec Kanban et modélisation avec UML.',
    'Frontend Developer Intern': 'Stagiaire développeur frontend', 'Developed the frontend of a website with React, building and refining its user interface during the internship.': 'Développement du frontend d’un site web avec React et amélioration de son interface utilisateur pendant le stage.',
    'IT Intern': 'Stagiaire en informatique', 'Gained practical experience installing, configuring, and troubleshooting computer hardware components.': 'Expérience pratique dans l’installation, la configuration et le dépannage de composants informatiques.',
    'Mentor': 'Mentor', 'Mentored IEEE RAS IIT SBC members and contributed as a speaker to an IoT Foundation workshop, introducing connected technologies and practical hardware applications.': 'Accompagnement des membres de l’IEEE RAS IIT SBC et intervention lors d’un atelier sur les fondamentaux de l’IoT, les technologies connectées et leurs applications matérielles.',
    'Chair': 'Président', 'Led the IEEE RAS IIT SBC, delivered an Introduction to Arduino workshop, and contributed to an IEEE TRSYP robotics project.': 'Direction de l’IEEE RAS IIT SBC, animation d’un atelier d’introduction à Arduino et contribution à un projet de robotique IEEE TRSYP.',
    'Developed a mini self-driving car using computer vision and embedded AI to detect and track objects, recognize traffic lights, follow lanes, and make basic navigation decisions.': 'Développement d’une mini-voiture autonome avec vision par ordinateur et IA embarquée pour détecter et suivre des objets, reconnaître les feux, suivre les voies et prendre des décisions de navigation.',
    'Project Manager': 'Chef de projet', 'Managed projects for the IEEE RAS IIT Student Branch Chapter.': 'Gestion de projets pour le Student Branch Chapter IEEE RAS de l’IIT.', 'Scout Leader': 'Chef scout', 'Served as a scout leader since 2019.': 'Chef scout depuis 2019.',
    'Leadership': 'Leadership', 'Mentoring': 'Mentorat', 'Workshop speaking': 'Animation d’ateliers', 'Technical workshops': 'Ateliers techniques', 'Project management': 'Gestion de projet', 'Teamwork': 'Travail d’équipe', 'Communication': 'Communication',
    'TECHNICAL TOOLKIT': 'COMPÉTENCES TECHNIQUES', 'Different layers.': 'Différentes couches.', 'Connected expertise.': 'Des compétences complémentaires.', 'The languages, frameworks, and tools I work with — from a microcontroller to a deployed application.': 'Les langages, frameworks et outils que j’utilise, du microcontrôleur à l’application déployée.',
    'Programming languages': 'Langages de programmation', 'Embedded & IoT': 'Systèmes embarqués et IoT', 'Frontend & mobile': 'Frontend et mobile', 'Backend': 'Backend', 'Databases': 'Bases de données', 'Tools': 'Outils', 'Testing & QA': 'Tests et assurance qualité', 'Languages': 'Langues', 'Professional strengths': 'Atouts professionnels',
    'Firmware development': 'Développement firmware', 'Sensors & actuators': 'Capteurs et actionneurs', 'API testing': 'Tests API', 'Functional testing': 'Tests fonctionnels', 'Integration testing': 'Tests d’intégration', 'System testing': 'Tests système', 'Regression testing': 'Tests de régression', 'Arabic (native)': 'Arabe (langue maternelle)', 'English (B1)': 'Anglais (B1)', 'French (B1)': 'Français (B1)', 'Leadership and team motivation': 'Leadership et motivation d’équipe', 'Decision-making and problem-solving': 'Prise de décision et résolution de problèmes', 'Stress management': 'Gestion du stress', 'Clear team communication': 'Communication claire en équipe',
    'SELECTED WORK': 'PROJETS SÉLECTIONNÉS', 'Code that leaves': 'Du code qui dépasse', 'the screen.': 'l’écran.', 'Full-stack applications and connected systems built to solve real-world problems.': 'Applications full-stack et systèmes connectés conçus pour répondre à des besoins concrets.',
    'Smart Irrigation System': 'Système d’irrigation intelligent', 'A connected irrigation platform linking a mobile app and web dashboard to backend services and an ESP32-S3 field controller.': 'Une plateforme d’irrigation connectée reliant une application mobile et un tableau de bord web aux services backend et à un contrôleur ESP32-S3 sur le terrain.',
    'I contributed across the connected irrigation stack.': 'J’ai contribué à l’ensemble de la plateforme d’irrigation connectée.',
    'I contributed Spring Boot and PostgreSQL backend features for device management, irrigation programs, logs, and live status, along with React dashboard features for monitoring, configuration, reporting, and irrigation management.': 'J’ai développé des fonctionnalités backend avec Spring Boot et PostgreSQL pour gérer les appareils, les programmes d’irrigation, les journaux et les états en direct, ainsi que des fonctions React de supervision, configuration, rapport et gestion de l’irrigation.',
    'I developed Flutter app features for onboarding, scheduling, remote valve control, and monitoring. I integrated REST/JSON APIs and MQTT synchronization across the apps, backend, and controllers, and added Firebase Cloud Messaging alerts.': 'J’ai développé avec Flutter la configuration initiale, la programmation, le contrôle à distance des vannes et la supervision. J’ai intégré les API REST/JSON et la synchronisation MQTT entre les applications, le backend et les contrôleurs, ainsi que les alertes Firebase Cloud Messaging.',
    'I also developed ESP32-S3 firmware and TFT pages for Wi-Fi onboarding, irrigation and valve control, state synchronization, pressure and sensor monitoring, and HTTPS OTA updates. I tested APIs and end-to-end integrations across the platform, tracked work in Jira with Scrum, and used Docker and Git in the development workflow.': 'J’ai également développé le firmware ESP32-S3 et les écrans TFT pour la connexion Wi-Fi, le contrôle de l’irrigation et des vannes, la synchronisation des états, le suivi de la pression et des capteurs, et les mises à jour OTA par HTTPS. J’ai testé les API et les intégrations de bout en bout, suivi le travail avec Jira et Scrum, et utilisé Docker et Git.',
    'THE PROBLEM': 'LE PROBLÈME', 'Irrigation shouldn’t depend on being there.': 'L’irrigation ne devrait pas nécessiter une présence sur place.', 'Manual irrigation offers limited remote control and visibility into what is happening at the pump, valves, and controller.': 'L’irrigation manuelle offre peu de contrôle à distance et de visibilité sur la pompe, les vannes et le contrôleur.',
    'THE SOLUTION': 'LA SOLUTION', 'One connected system, from app to field.': 'Un système connecté, de l’application au terrain.', 'People can set up the controller, manage irrigation remotely, and still use its local screen in the field.': 'L’utilisateur peut configurer le contrôleur, gérer l’irrigation à distance et continuer à utiliser son écran local sur le terrain.',
    'MY CONTRIBUTION': 'MA CONTRIBUTION', 'BlueBox in the field': 'BlueBox sur le terrain', 'Connected irrigation hardware': 'Matériel d’irrigation connecté', 'Technical overview': 'Aperçu technique', 'Architecture, capabilities, and tools': 'Architecture, fonctionnalités et outils', 'HOW THE WHOLE SYSTEM FITS TOGETHER': 'VUE D’ENSEMBLE DU SYSTÈME', 'Phone, services, controller, field.': 'Téléphone, services, contrôleur et terrain.', 'I contributed features across the mobile app, web dashboard, backend services, and embedded controller, integrating their APIs and device messaging as part of one platform.': 'J’ai contribué à l’application mobile, au tableau de bord web, aux services backend et au contrôleur embarqué en intégrant leurs API et leurs échanges avec les appareils.',
    'Mobile and web apps': 'Applications mobile et web', 'The mobile app guides controller setup and supports remote irrigation management. The web dashboard provides a wider view for configuration, monitoring, and reporting.': 'L’application mobile accompagne la configuration du contrôleur et la gestion à distance de l’irrigation. Le tableau de bord web offre une vue plus complète pour la configuration, la supervision et les rapports.',
    'Backend services': 'Services backend', 'The backend connects the applications to the controller and stores device, program, status, and activity data.': 'Le backend relie les applications au contrôleur et stocke les données des appareils, programmes, états et activités.',
    'Embedded controller': 'Contrôleur embarqué', 'Firmware provides local controls and status pages, joins Wi-Fi, synchronizes with the backend, and integrates the irrigation logic.': 'Le firmware fournit les commandes et états locaux, se connecte au Wi-Fi, se synchronise avec le backend et gère la logique d’irrigation.',
    'Field hardware': 'Matériel sur le terrain', 'Controller blocks operate the pump and valves and provide readings such as water pressure. Firmware can be updated remotely over HTTPS.': 'Le contrôleur pilote la pompe et les vannes et recueille des mesures comme la pression de l’eau. Le firmware peut être mis à jour à distance via HTTPS.',
    'HOW DATA MOVES': 'CIRCULATION DES DONNÉES', 'What the system supports': 'Fonctionnalités du système', 'TECHNOLOGY STACK': 'ENVIRONNEMENT TECHNIQUE', 'Wi-Fi onboarding · access point to backend': 'Configuration Wi-Fi · du point d’accès au backend', 'OTA firmware update · HTTPS and reboot': 'Mise à jour OTA du firmware · HTTPS et redémarrage', 'Embedded controller · system architecture': 'Contrôleur embarqué · architecture système', 'Controller TFT home screen': 'Écran d’accueil TFT du contrôleur', 'Mobile app · Irrigation schedule': 'Application mobile · programmation de l’irrigation', 'Mobile app, controller, and backend': 'Application mobile, contrôleur et backend',
    'Commercial Management Web Application': 'Application web de gestion commerciale', 'Customer storefront · Orders · Quotes · Admin portal': 'Boutique client · Commandes · Devis · Portail admin', 'A web platform for SECOME customers to browse metal products, place orders, and retrieve quotes, with a secure administration area for day-to-day commercial operations.': 'Une plateforme web permettant aux clients de SECOME de consulter les produits métalliques, passer commande et récupérer des devis, avec un espace sécurisé pour la gestion commerciale quotidienne.',
    'Product, customer, order, and quote workflows relied on disconnected or manual processes, making information harder to find and follow for both customers and administrators.': 'La gestion des produits, clients, commandes et devis reposait sur des processus manuels ou dispersés, compliquant le suivi pour les clients comme pour les administrateurs.',
    'Built a responsive customer storefront and a protected admin workspace over a service-based backend, bringing the product catalog, orders, quotes, and customer records into one application.': 'Création d’une boutique client adaptative et d’un espace d’administration sécurisé sur un backend composé de services, réunissant le catalogue, les commandes, les devis et les dossiers clients.',
    'I developed the customer and administration workflows.': 'J’ai développé les parcours client et administration.', 'THE CHALLENGE': 'LE DÉFI', 'Make product and order information easier to manage.': 'Simplifier la gestion des produits et des commandes.', 'THE SOLUTION': 'LA SOLUTION', 'One connected path from products to quotes.': 'Un parcours unifié, des produits aux devis.',
    'Implemented the product storefront, cart, delivery checkout, and order submission. The order flow produces a quote that customers can look up by email and download as a PDF.': 'Mise en place de la boutique, du panier, de la livraison et de la validation des commandes. Le parcours génère un devis que le client peut rechercher par e-mail et télécharger en PDF.',
    'Built administration screens for product management, customer records, order tracking, and quote review. Administrators can update the catalog, follow order status, and validate or respond to quotes.': 'Création des écrans d’administration pour les produits, les dossiers clients, le suivi des commandes et la revue des devis. Les administrateurs peuvent actualiser le catalogue, suivre les commandes et valider ou commenter les devis.',
    'Connected the React interface to Spring Boot services through Spring Cloud routing and an API Gateway, with Spring Data JPA and MySQL for persistence.': 'Connexion de l’interface React aux services Spring Boot via Spring Cloud et une passerelle API, avec Spring Data JPA et MySQL pour la persistance.',
    'Tested individual REST services with Postman and checked frontend/backend integration. Organized development with Kanban and documented the design with MVC concepts and UML use-case, sequence, and class diagrams.': 'Test des services REST avec Postman et vérification de l’intégration frontend/backend. Organisation avec Kanban et documentation de la conception à l’aide des concepts MVC et de diagrammes UML de cas d’utilisation, séquence et classes.',
    'Customer storefront': 'Boutique client', 'Administration portal': 'Portail d’administration', 'Customer and admin workflows over shared services.': 'Parcours client et admin sur des services partagés.', 'APPLICATION ARCHITECTURE': 'ARCHITECTURE DE L’APPLICATION', 'METHOD & DESIGN': 'MÉTHODE ET CONCEPTION', 'TOOLS & TECHNOLOGIES': 'OUTILS ET TECHNOLOGIES',
    'Customers browse the product catalog, add items to a cart, enter delivery details, submit an order, and retrieve generated quotes.': 'Les clients consultent le catalogue, ajoutent des articles au panier, saisissent leurs informations de livraison, passent commande et récupèrent les devis générés.',
    'Administrators use a sign-in area and dashboard to manage products and customers and follow orders and quotes.': 'Les administrateurs disposent d’un espace de connexion et d’un tableau de bord pour gérer les produits et les clients, et suivre commandes et devis.',
    'The backend is organized as MVC microservices, with an API Gateway routing requests and Spring Cloud supporting service configuration and discovery.': 'Le backend est organisé en microservices MVC. Une passerelle API achemine les requêtes et Spring Cloud prend en charge la configuration et la découverte des services.',
    'Relational records cover customers, products, orders, and quotes. REST endpoints and frontend/backend integration were checked during development.': 'La base relationnelle gère les clients, produits, commandes et devis. Les API REST et l’intégration frontend/backend ont été vérifiées pendant le développement.',
    'Browse products and view categories, descriptions, and prices.': 'Consulter les produits, catégories, descriptions et prix.', 'Add products to a cart, change quantities, and see the total update.': 'Ajouter des produits au panier, modifier les quantités et voir le total actualisé.', 'Submit an order with delivery information.': 'Passer une commande avec les informations de livraison.', 'Find quotes using an email address and download them as PDFs.': 'Rechercher les devis avec une adresse e-mail et les télécharger en PDF.',
    'Review product, order, quote, and customer counts on the dashboard.': 'Consulter les nombres de produits, commandes, devis et clients sur le tableau de bord.', 'Add, edit, and remove products and maintain catalog details.': 'Ajouter, modifier et supprimer des produits et gérer le catalogue.', 'Review customer records and track incoming orders and their status.': 'Consulter les dossiers clients et suivre les commandes et leur état.', 'Review and validate quotes, send a response, and make quote PDFs available.': 'Examiner et valider les devis, envoyer une réponse et mettre les PDF à disposition.',
    'Customer storefront · React · Axios · Bootstrap': 'Boutique client · React · Axios · Bootstrap', 'Customers browse the product catalog, add items to a cart, enter delivery details, submit an order, and retrieve generated quotes.': 'Les clients consultent le catalogue, ajoutent des articles au panier, saisissent leurs informations de livraison, passent commande et récupèrent les devis générés.',
    'Car Analyzer – Intelligent Vehicle Diagnostics System': 'Car Analyzer – système intelligent de diagnostic automobile', 'Developed a Flutter mobile application for real-time vehicle monitoring and data analysis. It analyzes sensor readings and driving history to assess engine health, battery status, and fuel consumption, presenting clear, actionable diagnostic insights.': 'Développement d’une application mobile Flutter pour superviser les véhicules et analyser leurs données en temps réel. Le système analyse les mesures des capteurs et l’historique de conduite afin d’évaluer le moteur, la batterie et la consommation de carburant, puis présente des diagnostics clairs et exploitables.',
    'Shows vehicle details and live dashboard readings, including speed and engine data.': 'Affiche les détails du véhicule et les mesures en direct, notamment la vitesse et les données moteur.', 'Analyzes driving history, engine health, battery status, and fuel consumption.': 'Analyse l’historique de conduite, l’état du moteur et de la batterie, ainsi que la consommation de carburant.', 'Displays sensor status and flags readings that may need attention.': 'Affiche l’état des capteurs et signale les mesures qui nécessitent une vérification.',
    'Mini Autonomous Car': 'Mini-voiture autonome', 'Built for IEEE TRSYP, this mini self-driving car uses computer vision and embedded AI to detect and track surrounding objects, recognize traffic lights, follow lanes, and make basic navigation decisions.': 'Réalisée pour IEEE TRSYP, cette mini-voiture autonome utilise la vision par ordinateur et l’IA embarquée pour détecter et suivre les objets, reconnaître les feux de circulation, suivre les voies et prendre des décisions de navigation simples.',
    'Detected and tracked surrounding objects in real time.': 'Détection et suivi des objets environnants en temps réel.', 'Recognized traffic lights and responded to their signals.': 'Reconnaissance des feux de circulation et réaction à leurs signaux.', 'Followed lanes and made basic autonomous navigation decisions.': 'Suivi des voies et prise de décisions de navigation autonome.',
    'After-Sales Service Management Web App': 'Application web de gestion du service après-vente', 'Built a role-based after-sales portal where customers submit product complaints and follow repair interventions, while administrators manage the product catalog and service workflow.': 'Création d’un portail après-vente avec des rôles distincts : les clients déposent des réclamations et suivent les réparations, tandis que les administrateurs gèrent le catalogue et le processus de service.',
    'Client area for submitting complaints and viewing warranty status, repair interventions, and spare parts used.': 'Espace client pour déposer des réclamations et consulter la garantie, les réparations et les pièces utilisées.', 'Admin tools for managing catalog articles, complaints, interventions, and spare parts.': 'Outils admin pour gérer les articles du catalogue, les réclamations, les interventions et les pièces détachées.', 'Warranty-aware service costs, including labor and replacement parts.': 'Calcul des coûts de service selon la garantie, la main-d’œuvre et les pièces de remplacement.', 'Key responsibilities': 'Responsabilités principales', 'Technologies': 'Technologies', 'Explore project': 'Découvrir le projet', 'View source on GitHub': 'Voir le code sur GitHub',
    'Always': 'Toujours', 'building forward.': 'aller de l’avant.', 'A foundation in software.': 'Des bases solides en informatique.', 'An ongoing commitment to learning.': 'La volonté constante d’apprendre.', 'In Progress': 'En cours', 'Completed': 'Terminé', 'Study areas': 'Domaines d’étude', 'Available for full-time daytime work': 'Disponible à temps plein en journée',
    'Engineering Cycle in Computer Science': 'Cycle ingénieur en informatique', 'Graduate in Computer Science and Information Systems.': 'Diplômé en informatique et systèmes d’information.', 'Bachelor’s Degree in Computer Science and Information Systems': 'Licence en informatique et systèmes d’information', 'Baccalaureate in Technical Sciences': 'Baccalauréat en sciences techniques', 'Technical Sciences baccalaureate.': 'Baccalauréat en sciences techniques.', 'Evening classes': 'Cours du soir', 'Computer Science': 'Informatique', 'Information Systems': 'Systèmes d’information', 'Technical Sciences': 'Sciences techniques', 'Evening classes': 'Cours du soir',
    'LET’S CONNECT': 'PRENONS CONTACT', 'Let’s build': 'Construisons', 'something': 'quelque chose de', 'great.': 'remarquable.', 'I’m open to opportunities in full-stack development, embedded systems, IoT, mobile development, and software testing.': 'Je suis ouvert aux opportunités en développement full-stack, systèmes embarqués, IoT, applications mobiles et tests logiciels.', 'Have a role or a project in mind?': 'Vous avez un poste ou un projet en tête ?', 'I’d love to hear about it.': 'Je serais ravi d’en discuter.', 'Available for full-time daytime work · Evening studies': 'Disponible à temps plein en journée · Études le soir', 'Start a conversation': 'Commençons à échanger', 'SAY HELLO': 'DIRE BONJOUR', 'Name': 'Nom', 'Email': 'E-mail', 'Subject': 'Objet', 'Message': 'Message', 'Your name': 'Votre nom', 'An opportunity, a project, an introduction…': 'Une opportunité, un projet, une prise de contact…', 'Tell me a little about what you have in mind.': 'Dites-m’en un peu plus sur votre idée.', 'Leave this empty': 'Laisser ce champ vide', 'Sending…': 'Envoi en cours…', 'Copy message': 'Copier le message', 'Send message': 'Envoyer le message', 'Open email draft': 'Ouvrir le brouillon d’e-mail', 'This only copies a message. It will not be sent; use the listed contact details to send it.': 'Cette action copie le message sans l’envoyer. Utilisez les coordonnées affichées pour l’envoyer.', 'Your details are used to respond to your inquiry. This form uses an external message delivery service.': 'Vos coordonnées servent à répondre à votre demande. Ce formulaire utilise un service externe d’envoi.', 'This opens your email app with a draft for you to review and send.': 'Votre application e-mail s’ouvrira avec un brouillon à relire et envoyer.', 'Please complete each field before continuing.': 'Veuillez remplir tous les champs avant de continuer.', 'Message copied. It has not been sent. Use the contact details on this page to send it.': 'Message copié. Il n’a pas été envoyé. Utilisez les coordonnées de cette page pour l’envoyer.', 'Select and copy your message below. It has not been sent.': 'Sélectionnez et copiez votre message ci-dessous. Il n’a pas été envoyé.', 'Your email app has been requested. Review and send the draft there. Nothing is sent by this website.': 'Votre application e-mail va s’ouvrir. Vérifiez le brouillon et envoyez-le. Aucun message n’est envoyé par ce site.', 'Thank you. Your message has been submitted successfully.': 'Merci. Votre message a bien été envoyé.', 'Your message could not be sent. Please try again': 'Votre message n’a pas pu être envoyé. Veuillez réessayer', ' or use the email link.': ' ou utiliser le lien e-mail.', ' later.': ' plus tard.', 'Email details coming soon': 'Coordonnées e-mail bientôt disponibles', 'Your message': 'Votre message',
    'Back to top': 'Retour en haut', 'All rights reserved.': 'Tous droits réservés.', 'Thoughtfully built. Always evolving.': 'Conçu avec soin. En constante évolution.',
    'System flows and architecture': 'Flux système et architecture', 'Visual guides to Wi-Fi setup, controller synchronization, and firmware updates.': 'Schémas de configuration Wi-Fi, de synchronisation du contrôleur et de mise à jour du firmware.', 'Product views': 'Vues du produit', 'Controller screen, mobile schedule, and system overview.': 'Écran du contrôleur, programme mobile et vue d’ensemble du système.', 'Hide mobile app screen album': 'Masquer les écrans de l’application mobile', 'Browse mobile app screen album': 'Parcourir les écrans de l’application mobile', 'screens': 'écrans', 'BlueBox mobile app screens': 'Écrans de l’application mobile BlueBox', 'Sign-in, account setup, password recovery, valve onboarding, and irrigation scheduling.': 'Connexion, création de compte, récupération du mot de passe, ajout de vannes et programmation de l’irrigation.', 'Hide embedded screen album': 'Masquer les écrans embarqués', 'Browse embedded screen album': 'Parcourir les écrans embarqués', 'Embedded controller screens': 'Écrans du contrôleur embarqué', 'Select any screen to view it larger. Use the arrow keys or buttons to browse.': 'Sélectionnez un écran pour l’agrandir. Utilisez les flèches ou les boutons pour parcourir les images.', 'PROJECT GALLERY': 'GALERIE DU PROJET', 'Close image viewer': 'Fermer la visionneuse', 'Previous screenshot': 'Capture précédente', 'Next screenshot': 'Capture suivante', 'Use left/right arrow keys to browse | Esc to close': 'Utilisez les flèches gauche/droite pour parcourir | Échap pour fermer', 'Image unavailable': 'Image indisponible', 'Controller & valves': 'Contrôleur et vannes', 'Mobile application': 'Application mobile', 'Web dashboard': 'Tableau de bord web', 'Product image coming soon': 'Image du produit bientôt disponible', 'application screens': 'écrans de l’application', 'Browse selected screens from the': 'Parcourir une sélection d’écrans de', 'Open screenshot:': 'Ouvrir la capture :', 'Close navigation': 'Fermer la navigation', 'Open navigation': 'Ouvrir la navigation',
    'Caption': 'Légende', 'Computer hardware': 'Matériel informatique', 'Installation': 'Installation', 'Configuration': 'Configuration', 'Troubleshooting': 'Dépannage', 'Frontend development': 'Développement frontend', 'Web UI': 'Interface web', 'Robotics project': 'Projet de robotique', 'Full-stack development': 'Développement full-stack', 'Full-stack & IoT internship': 'Stage full-stack et IoT', 'Full-stack internship': 'Stage en développement full-stack', 'Computer vision': 'Vision par ordinateur', 'Object detection': 'Détection d’objets', 'Traffic-light recognition': 'Reconnaissance des feux', 'Lane following': 'Suivi de voie', 'Autonomous navigation': 'Navigation autonome', 'Vehicle diagnostics': 'Diagnostic automobile', 'Sensor data': 'Données de capteurs', 'Data visualization': 'Visualisation des données',
  },
  ar: {
    'Email': 'البريد الإلكتروني', 'GitHub details coming soon': 'ستتوفر معلومات GitHub قريباً', 'Academic project': 'مشروع أكاديمي', 'Data and validation': 'البيانات والتحقق', 'application.': 'التطبيق.',
    'Your message could not be sent. Please try again or use the email link.': 'تعذر إرسال رسالتك. يرجى المحاولة مجدداً أو استخدام رابط البريد الإلكتروني.', 'Your message could not be sent. Please try again later.': 'تعذر إرسال رسالتك. يرجى المحاولة مجدداً لاحقاً.',
    'The React client sends REST requests through the Spring Cloud API Gateway to the Spring Boot services. Spring Data JPA persists catalog, customer, order, and quote data in MySQL.': 'يرسل عميل React طلبات REST عبر بوابة Spring Cloud API إلى خدمات Spring Boot. وتحفظ Spring Data JPA بيانات الكتالوج والعملاء والطلبات وعروض الأسعار في MySQL.',
    'Currently continuing my studies in an evening program.': 'أواصل دراستي حالياً ضمن برنامج مسائي.',
    'Mohamed Yahya Sellami | Full-Stack, IoT & Software Testing': 'محمد يحيى سلامي | تطوير Full-Stack وإنترنت الأشياء واختبار البرمجيات',
    'Home': 'الرئيسية', 'Experience': 'الخبرات', 'Skills': 'المهارات', 'Projects': 'المشاريع', 'Education': 'التعليم', 'Contact': 'اتصل بي', 'Main navigation': 'التنقل الرئيسي', 'Skip to content': 'انتقل إلى المحتوى', 'Download CV': 'تحميل السيرة الذاتية', 'Switch to light mode': 'التبديل إلى الوضع الفاتح', 'Switch to dark mode': 'التبديل إلى الوضع الداكن',
    'Language': 'اللغة', 'Hi, I’m': 'مرحباً، أنا', 'Open to full-time opportunities': 'متاح لفرص العمل بدوام كامل', 'Junior Full-Stack & IoT Developer | Software Testing': 'مطور Full-Stack وإنترنت الأشياء | اختبار البرمجيات', 'Full-stack development, embedded IoT, and software testing.': 'تطوير Full-Stack وإنترنت الأشياء المضمن واختبار البرمجيات.', 'View projects': 'استعرض المشاريع', 'ABOUT ME': 'نبذة عني', 'ENGINEERING MINDSET': 'عقلية هندسية',
    'I build full-stack and IoT systems that connect software with the physical world.': 'أطوّر أنظمة Full-Stack وإنترنت الأشياء التي تربط البرمجيات بالعالم الحقيقي.',
    'Computer Science and Information Systems graduate with hands-on experience in full-stack development, IoT systems, and software testing. Experienced in API, integration, and system testing across backend, web, mobile, and embedded environments. Skilled in Spring Boot, PostgreSQL, React, Flutter, C/C++, REST APIs, MQTT, and hardware–software integration. Strong understanding of end-to-end system behavior with a focus on reliability, software quality, and problem solving.': 'خريج علوم الحاسوب ونظم المعلومات، ولدي خبرة عملية في تطوير Full-Stack وأنظمة إنترنت الأشياء واختبار البرمجيات. أجريت اختبارات واجهات API والتكامل والأنظمة في بيئات الخوادم والويب والهواتف والأنظمة المضمنة. أمتلك خبرة في Spring Boot وPostgreSQL وReact وFlutter وC/C++ وواجهات REST وMQTT ودمج الأجهزة بالبرمجيات. أركز على موثوقية الأنظمة وجودة البرمجيات وحل المشكلات.',
    'Embedded systems': 'الأنظمة المضمنة', 'Full-stack software': 'برمجيات Full-Stack', 'Reliable delivery': 'تسليم موثوق', 'Available for daytime work.': 'متاح للعمل خلال النهار.', 'My engineering classes are in the evening.': 'تُعقد دراستي الهندسية في المساء.',
    'EXPERIENCE': 'الخبرات', 'Engineering in practice.': 'الهندسة في التطبيق العملي.', 'Hands-on work across software, connected devices, and the places where they meet.': 'خبرة عملية في البرمجيات والأجهزة المتصلة ودمجها معاً.', 'Professional internships': 'التدريبات المهنية', 'Software, IoT, and technical support roles.': 'مهام في البرمجيات وإنترنت الأشياء والدعم التقني.', 'Leadership & community': 'القيادة والمجتمع', 'IEEE RAS IIT SBC and Scouts.': 'IEEE RAS IIT SBC والكشافة.', 'ROLES': 'الأدوار', 'Professional internship': 'تدريب مهني', 'Associative experience': 'نشاط جمعياتي', 'Explore the project': 'استكشف المشروع',
    'Full-Stack & IoT Developer Intern': 'متدرب في تطوير Full-Stack وإنترنت الأشياء', 'Contributed across the BlueBox smart irrigation platform, building backend, web, and mobile features alongside ESP32-S3 firmware and controller integration.': 'ساهمت في تطوير منصة BlueBox للري الذكي، من خلال بناء وظائف الخادم والويب والهاتف، وتطوير برنامج ESP32-S3 المضمن ودمج وحدة التحكم.',
    'Developed Java and Spring Boot REST APIs with PostgreSQL for device management, irrigation programs, logs, and live status; used Docker for the backend and database development environment.': 'طورت واجهات REST باستخدام Java وSpring Boot وPostgreSQL لإدارة الأجهزة وبرامج الري والسجلات والحالة المباشرة. واستخدمت Docker لتهيئة بيئة تطوير الخادم وقاعدة البيانات.',
    'Built React dashboard and Flutter mobile features for monitoring, configuration, reporting, controller onboarding, irrigation scheduling, and remote valve control.': 'طورت وظائف باستخدام React وFlutter للمراقبة والإعداد والتقارير وربط وحدة التحكم وجدولة الري والتحكم عن بُعد في الصمامات.',
    'Integrated REST/JSON and MQTT data exchange between applications, backend services, and ESP32-S3 controllers, and added Firebase Cloud Messaging alerts.': 'دمجت تبادل البيانات عبر REST/JSON وMQTT بين التطبيقات وخدمات الخادم ووحدات ESP32-S3، وأضفت التنبيهات باستخدام Firebase Cloud Messaging.',
    'Developed C/C++ firmware and the TFT interface for irrigation control, Wi-Fi onboarding, valve and pump states, sensor and pressure monitoring, and HTTPS OTA updates.': 'طورت البرنامج المضمن وواجهة TFT باستخدام C/C++ للتحكم بالري والاتصال بشبكة Wi-Fi وحالات الصمامات والمضخة ومراقبة المستشعرات والضغط وتحديثات OTA عبر HTTPS.',
    'Performed API, integration, and system testing across web, mobile, backend, and IoT components; investigated defects and verified fixes to improve reliability.': 'نفذت اختبارات API والتكامل والنظام لمكونات الويب والهاتف والخادم وإنترنت الأشياء، وتابعت الأخطاء وتحققت من إصلاحها لتحسين الموثوقية.',
    'Used Git for version control and Jira to track tasks, blockers, and dependencies; contributed to Scrum planning, daily Scrum, reviews, retrospectives, and backlog refinement across the team.': 'استخدمت Git لإدارة الإصدارات وJira لمتابعة المهام والعوائق والاعتماديات، وشاركت في تخطيط Scrum والاجتماعات اليومية والمراجعات والاستعادات وتنقيح قائمة العمل.',
    'Full-Stack Development Intern': 'متدرب في تطوير Full-Stack', 'Developed a commercial management web application for SECOME, connecting a customer storefront with an administration portal and backend services.': 'طورت تطبيق ويب للإدارة التجارية في SECOME يربط واجهة العملاء ببوابة الإدارة وخدمات الخادم.',
    'Built customer flows for browsing products, managing a cart, placing orders, and retrieving downloadable PDF quotes.': 'أنشأت مسارات لتصفح المنتجات وإدارة السلة وإرسال الطلبات واسترجاع عروض الأسعار بصيغة PDF.', 'Implemented Spring Boot microservices with Spring Cloud routing, Spring Data JPA, and MySQL; developed the interface with React and Axios.': 'نفذت خدمات مصغرة باستخدام Spring Boot وتوجيه Spring Cloud وSpring Data JPA وMySQL، وطورت الواجهة باستخدام React وAxios.', 'Created protected administration workflows for the product catalog, customers, orders, and quote review and approval.': 'أنشأت وظائف إدارية محمية لإدارة المنتجات والعملاء والطلبات ومراجعة عروض الأسعار والموافقة عليها.', 'Tested REST endpoints with Postman and checked integration between the frontend and backend; used Kanban and UML to organize and model the work.': 'اختبرت واجهات REST باستخدام Postman وتحققت من تكامل الواجهة الأمامية والخلفية، واستخدمت Kanban وUML لتنظيم العمل ونمذجته.',
    'Frontend Developer Intern': 'متدرب في تطوير الواجهات الأمامية', 'Developed the frontend of a website with React, building and refining its user interface during the internship.': 'طورت الواجهة الأمامية لموقع باستخدام React وعملت على بناء واجهة المستخدم وتحسينها خلال فترة التدريب.', 'IT Intern': 'متدرب تقنية معلومات', 'Gained practical experience installing, configuring, and troubleshooting computer hardware components.': 'اكتسبت خبرة عملية في تركيب مكونات الحاسوب وتهيئتها واستكشاف أعطالها.',
    'Mentor': 'مرشد', 'Mentored IEEE RAS IIT SBC members and contributed as a speaker to an IoT Foundation workshop, introducing connected technologies and practical hardware applications.': 'أرشدت أعضاء IEEE RAS IIT SBC وشاركت كمتحدث في ورشة أساسيات إنترنت الأشياء، وقدمت التقنيات المتصلة وتطبيقاتها العملية على الأجهزة.', 'Chair': 'رئيس الفرع', 'Led the IEEE RAS IIT SBC, delivered an Introduction to Arduino workshop, and contributed to an IEEE TRSYP robotics project.': 'قدت فرع IEEE RAS IIT SBC وقدمت ورشة تمهيدية حول Arduino وساهمت في مشروع روبوتات IEEE TRSYP.', 'Developed a mini self-driving car using computer vision and embedded AI to detect and track objects, recognize traffic lights, follow lanes, and make basic navigation decisions.': 'طورت سيارة ذاتية القيادة صغيرة باستخدام الرؤية الحاسوبية والذكاء الاصطناعي المضمن لاكتشاف الأجسام وتتبعها والتعرف على إشارات المرور واتباع المسارات واتخاذ قرارات تنقل أساسية.', 'Project Manager': 'مدير مشاريع', 'Managed projects for the IEEE RAS IIT Student Branch Chapter.': 'أدرت مشاريع فرع IEEE RAS الطلابي في IIT.', 'Scout Leader': 'قائد كشافة', 'Served as a scout leader since 2019.': 'أعمل قائداً للكشافة منذ عام 2019.',
    'Leadership': 'القيادة', 'Mentoring': 'الإرشاد', 'Workshop speaking': 'تقديم ورش العمل', 'Technical workshops': 'ورش تقنية', 'Project management': 'إدارة المشاريع', 'Teamwork': 'العمل الجماعي', 'Communication': 'التواصل',
    'TECHNICAL TOOLKIT': 'المهارات التقنية', 'Different layers.': 'طبقات مختلفة.', 'Connected expertise.': 'خبرات مترابطة.', 'The languages, frameworks, and tools I work with — from a microcontroller to a deployed application.': 'اللغات وأطر العمل والأدوات التي أستخدمها، من المتحكم الدقيق إلى التطبيقات المنشورة.', 'Programming languages': 'لغات البرمجة', 'Embedded & IoT': 'الأنظمة المضمنة وإنترنت الأشياء', 'Frontend & mobile': 'الواجهات الأمامية والهواتف', 'Backend': 'الخلفية', 'Databases': 'قواعد البيانات', 'Tools': 'الأدوات', 'Testing & QA': 'الاختبار وضمان الجودة', 'Languages': 'اللغات', 'Professional strengths': 'المهارات المهنية', 'Firmware development': 'تطوير البرامج المضمنة', 'Sensors & actuators': 'المستشعرات والمشغلات', 'API testing': 'اختبار API', 'Functional testing': 'الاختبار الوظيفي', 'Integration testing': 'اختبار التكامل', 'System testing': 'اختبار الأنظمة', 'Regression testing': 'اختبار الانحدار', 'Arabic (native)': 'العربية (اللغة الأم)', 'English (B1)': 'الإنجليزية (B1)', 'French (B1)': 'الفرنسية (B1)', 'Leadership and team motivation': 'القيادة وتحفيز الفريق', 'Decision-making and problem-solving': 'اتخاذ القرار وحل المشكلات', 'Stress management': 'إدارة الضغط', 'Clear team communication': 'التواصل الواضح ضمن الفريق',
    'SELECTED WORK': 'أعمال مختارة', 'Code that leaves': 'برمجيات تتجاوز', 'the screen.': 'حدود الشاشة.', 'Full-stack applications and connected systems built to solve real-world problems.': 'تطبيقات Full-Stack وأنظمة متصلة صُممت لحل مشكلات واقعية.', 'Smart Irrigation System': 'نظام ري ذكي', 'A connected irrigation platform linking a mobile app and web dashboard to backend services and an ESP32-S3 field controller.': 'منصة ري متصلة تربط تطبيق الهاتف ولوحة الويب بخدمات الخادم ووحدة تحكم ESP32-S3 ميدانية.', 'I contributed across the connected irrigation stack.': 'ساهمت في تطوير منظومة الري المتصلة بالكامل.',
    'I contributed Spring Boot and PostgreSQL backend features for device management, irrigation programs, logs, and live status, along with React dashboard features for monitoring, configuration, reporting, and irrigation management.': 'طورت وظائف خلفية باستخدام Spring Boot وPostgreSQL لإدارة الأجهزة وبرامج الري والسجلات والحالة المباشرة، بالإضافة إلى وظائف لوحة React للمراقبة والإعداد والتقارير وإدارة الري.', 'I developed Flutter app features for onboarding, scheduling, remote valve control, and monitoring. I integrated REST/JSON APIs and MQTT synchronization across the apps, backend, and controllers, and added Firebase Cloud Messaging alerts.': 'طورت باستخدام Flutter وظائف إعداد وحدة التحكم والجدولة والتحكم عن بُعد بالصمامات والمراقبة. ودمجت واجهات REST/JSON ومزامنة MQTT بين التطبيقات والخادم ووحدات التحكم، وأضفت تنبيهات Firebase Cloud Messaging.', 'I also developed ESP32-S3 firmware and TFT pages for Wi-Fi onboarding, irrigation and valve control, state synchronization, pressure and sensor monitoring, and HTTPS OTA updates. I tested APIs and end-to-end integrations across the platform, tracked work in Jira with Scrum, and used Docker and Git in the development workflow.': 'كما طورت برنامج ESP32-S3 المضمن وشاشات TFT لإعداد Wi-Fi والتحكم بالري والصمامات ومزامنة الحالات ومراقبة الضغط والمستشعرات وتحديثات OTA عبر HTTPS. اختبرت واجهات API والتكامل من البداية إلى النهاية، وتابعت العمل عبر Jira وScrum واستخدمت Docker وGit.',
    'THE PROBLEM': 'المشكلة', 'Irrigation shouldn’t depend on being there.': 'لا ينبغي أن يتطلب الري وجودك في المكان.', 'Manual irrigation offers limited remote control and visibility into what is happening at the pump, valves, and controller.': 'يوفر الري اليدوي تحكماً عن بُعد ورؤية محدودين لما يحدث في المضخة والصمامات ووحدة التحكم.', 'THE SOLUTION': 'الحل', 'One connected system, from app to field.': 'نظام متصل واحد من التطبيق إلى الحقل.', 'People can set up the controller, manage irrigation remotely, and still use its local screen in the field.': 'يمكن للمستخدم إعداد وحدة التحكم وإدارة الري عن بُعد واستخدام شاشتها المحلية في الحقل.', 'MY CONTRIBUTION': 'مساهمتي', 'BlueBox in the field': 'BlueBox في الميدان', 'Connected irrigation hardware': 'أجهزة ري متصلة', 'Technical overview': 'نظرة تقنية عامة', 'Architecture, capabilities, and tools': 'البنية والقدرات والأدوات', 'HOW THE WHOLE SYSTEM FITS TOGETHER': 'كيف يعمل النظام بالكامل', 'Phone, services, controller, field.': 'الهاتف والخدمات ووحدة التحكم والحقل.', 'I contributed features across the mobile app, web dashboard, backend services, and embedded controller, integrating their APIs and device messaging as part of one platform.': 'ساهمت في تطوير تطبيق الهاتف ولوحة الويب وخدمات الخادم ووحدة التحكم المضمنة، ودمجت واجهاتها ورسائل الأجهزة ضمن منصة واحدة.',
    'Mobile and web apps': 'تطبيقات الهاتف والويب', 'The mobile app guides controller setup and supports remote irrigation management. The web dashboard provides a wider view for configuration, monitoring, and reporting.': 'يساعد تطبيق الهاتف على إعداد وحدة التحكم وإدارة الري عن بُعد. وتوفر لوحة الويب عرضاً أوسع للإعداد والمراقبة والتقارير.', 'Backend services': 'خدمات الخادم', 'The backend connects the applications to the controller and stores device, program, status, and activity data.': 'يربط الخادم التطبيقات بوحدة التحكم ويحفظ بيانات الأجهزة والبرامج والحالة والنشاط.', 'Embedded controller': 'وحدة تحكم مضمنة', 'Firmware provides local controls and status pages, joins Wi-Fi, synchronizes with the backend, and integrates the irrigation logic.': 'يوفر البرنامج المضمن أدوات تحكم محلية وصفحات للحالة، ويتصل بشبكة Wi-Fi ويتزامن مع الخادم ويدير منطق الري.', 'Field hardware': 'أجهزة الحقل', 'Controller blocks operate the pump and valves and provide readings such as water pressure. Firmware can be updated remotely over HTTPS.': 'تتحكم الوحدة بالمضخة والصمامات وتوفر قراءات مثل ضغط المياه. ويمكن تحديث البرنامج المضمن عن بُعد عبر HTTPS.', 'HOW DATA MOVES': 'مسار البيانات', 'What the system supports': 'وظائف النظام', 'TECHNOLOGY STACK': 'التقنيات المستخدمة', 'Wi-Fi onboarding · access point to backend': 'إعداد Wi-Fi · من نقطة الوصول إلى الخادم', 'OTA firmware update · HTTPS and reboot': 'تحديث البرنامج OTA · HTTPS وإعادة التشغيل', 'Embedded controller · system architecture': 'وحدة التحكم المضمنة · بنية النظام', 'Controller TFT home screen': 'الشاشة الرئيسية TFT لوحدة التحكم', 'Mobile app · Irrigation schedule': 'تطبيق الهاتف · جدول الري', 'Mobile app, controller, and backend': 'تطبيق الهاتف ووحدة التحكم والخادم',
    'Commercial Management Web Application': 'تطبيق ويب للإدارة التجارية', 'Customer storefront · Orders · Quotes · Admin portal': 'متجر العملاء · الطلبات · عروض الأسعار · بوابة الإدارة', 'A web platform for SECOME customers to browse metal products, place orders, and retrieve quotes, with a secure administration area for day-to-day commercial operations.': 'منصة ويب لعملاء SECOME لاستعراض المنتجات المعدنية وإرسال الطلبات والحصول على عروض الأسعار، مع مساحة إدارة آمنة للعمليات التجارية اليومية.', 'Product, customer, order, and quote workflows relied on disconnected or manual processes, making information harder to find and follow for both customers and administrators.': 'اعتمدت عمليات المنتجات والعملاء والطلبات وعروض الأسعار على إجراءات يدوية ومتفرقة، مما صعّب العثور على المعلومات ومتابعتها للعملاء والإداريين.', 'Built a responsive customer storefront and a protected admin workspace over a service-based backend, bringing the product catalog, orders, quotes, and customer records into one application.': 'أنشأت متجر عملاء متجاوباً ومساحة إدارة محمية فوق خادم قائم على الخدمات، وجمعت كتالوج المنتجات والطلبات وعروض الأسعار وسجلات العملاء في تطبيق واحد.', 'I developed the customer and administration workflows.': 'طورت مسارات العمل الخاصة بالعملاء والإدارة.', 'THE CHALLENGE': 'التحدي', 'Make product and order information easier to manage.': 'تسهيل إدارة معلومات المنتجات والطلبات.', 'One connected path from products to quotes.': 'مسار متصل من المنتجات إلى عروض الأسعار.',
    'Implemented the product storefront, cart, delivery checkout, and order submission. The order flow produces a quote that customers can look up by email and download as a PDF.': 'نفذت متجر المنتجات وسلة التسوق وإدخال بيانات التوصيل وإرسال الطلب. وينشئ الطلب عرض سعر يستطيع العميل البحث عنه بالبريد الإلكتروني وتنزيله بصيغة PDF.', 'Built administration screens for product management, customer records, order tracking, and quote review. Administrators can update the catalog, follow order status, and validate or respond to quotes.': 'أنشأت شاشات إدارية لإدارة المنتجات وسجلات العملاء ومتابعة الطلبات ومراجعة عروض الأسعار. ويمكن للإداريين تحديث الكتالوج ومتابعة حالة الطلبات واعتماد عروض الأسعار أو الرد عليها.', 'Connected the React interface to Spring Boot services through Spring Cloud routing and an API Gateway, with Spring Data JPA and MySQL for persistence.': 'ربطت واجهة React بخدمات Spring Boot من خلال توجيه Spring Cloud وبوابة API، مع Spring Data JPA وMySQL لحفظ البيانات.', 'Tested individual REST services with Postman and checked frontend/backend integration. Organized development with Kanban and documented the design with MVC concepts and UML use-case, sequence, and class diagrams.': 'اختبرت خدمات REST باستخدام Postman وتحققت من تكامل الواجهات الأمامية والخلفية. نظمت التطوير باستخدام Kanban ووثقت التصميم بمفاهيم MVC ومخططات UML لحالات الاستخدام والتسلسل والفئات.',
    'Customer storefront': 'متجر العملاء', 'Administration portal': 'بوابة الإدارة', 'Customer and admin workflows over shared services.': 'مسارات العملاء والإدارة فوق خدمات مشتركة.', 'APPLICATION ARCHITECTURE': 'بنية التطبيق', 'METHOD & DESIGN': 'المنهجية والتصميم', 'TOOLS & TECHNOLOGIES': 'الأدوات والتقنيات', 'Customers browse the product catalog, add items to a cart, enter delivery details, submit an order, and retrieve generated quotes.': 'يتصفح العملاء كتالوج المنتجات ويضيفون العناصر إلى السلة ويدخلون بيانات التوصيل ويرسلون الطلب ويحصلون على عروض الأسعار.', 'Administrators use a sign-in area and dashboard to manage products and customers and follow orders and quotes.': 'يستخدم الإداريون صفحة تسجيل الدخول ولوحة التحكم لإدارة المنتجات والعملاء ومتابعة الطلبات وعروض الأسعار.', 'The backend is organized as MVC microservices, with an API Gateway routing requests and Spring Cloud supporting service configuration and discovery.': 'ينظم الخادم كخدمات مصغرة وفق MVC، وتوجه بوابة API الطلبات بينما يدعم Spring Cloud إعداد الخدمات واكتشافها.', 'Relational records cover customers, products, orders, and quotes. REST endpoints and frontend/backend integration were checked during development.': 'تضم قاعدة البيانات العلائقية سجلات العملاء والمنتجات والطلبات وعروض الأسعار. وتم التحقق من نقاط REST وتكامل الواجهات خلال التطوير.',
    'Browse products and view categories, descriptions, and prices.': 'تصفح المنتجات والفئات والأوصاف والأسعار.', 'Add products to a cart, change quantities, and see the total update.': 'أضف المنتجات إلى السلة وعدّل الكميات وشاهد تحديث الإجمالي.', 'Submit an order with delivery information.': 'أرسل طلباً مع معلومات التوصيل.', 'Find quotes using an email address and download them as PDFs.': 'اعثر على عروض الأسعار بالبريد الإلكتروني ونزّلها كملفات PDF.', 'Review product, order, quote, and customer counts on the dashboard.': 'راجع أعداد المنتجات والطلبات وعروض الأسعار والعملاء في لوحة التحكم.', 'Add, edit, and remove products and maintain catalog details.': 'أضف المنتجات وعدّلها واحذفها وأدر تفاصيل الكتالوج.', 'Review customer records and track incoming orders and their status.': 'راجع سجلات العملاء وتابع الطلبات الجديدة وحالتها.', 'Review and validate quotes, send a response, and make quote PDFs available.': 'راجع عروض الأسعار واعتمدها وأرسل رداً وأتح ملفات PDF.',
    'Car Analyzer – Intelligent Vehicle Diagnostics System': 'Car Analyzer – نظام ذكي لتشخيص المركبات', 'Developed a Flutter mobile application for real-time vehicle monitoring and data analysis. It analyzes sensor readings and driving history to assess engine health, battery status, and fuel consumption, presenting clear, actionable diagnostic insights.': 'طورت تطبيق هاتف باستخدام Flutter لمراقبة المركبات وتحليل البيانات في الوقت الفعلي. يحلل النظام قراءات المستشعرات وسجل القيادة لتقييم حالة المحرك والبطارية واستهلاك الوقود، ويقدم نتائج تشخيصية واضحة وقابلة للتطبيق.', 'Shows vehicle details and live dashboard readings, including speed and engine data.': 'يعرض تفاصيل المركبة وقراءات مباشرة مثل السرعة وبيانات المحرك.', 'Analyzes driving history, engine health, battery status, and fuel consumption.': 'يحلل سجل القيادة وحالة المحرك والبطارية واستهلاك الوقود.', 'Displays sensor status and flags readings that may need attention.': 'يعرض حالة المستشعرات وينبه إلى القراءات التي تتطلب الانتباه.', 'Mini Autonomous Car': 'سيارة ذاتية القيادة مصغرة', 'Built for IEEE TRSYP, this mini self-driving car uses computer vision and embedded AI to detect and track surrounding objects, recognize traffic lights, follow lanes, and make basic navigation decisions.': 'طورت هذه السيارة ذاتية القيادة الصغيرة لصالح IEEE TRSYP، وتستخدم الرؤية الحاسوبية والذكاء الاصطناعي المضمن لاكتشاف الأجسام المحيطة وتتبعها والتعرف على إشارات المرور واتباع المسارات واتخاذ قرارات تنقل أساسية.', 'Detected and tracked surrounding objects in real time.': 'اكتشاف الأجسام المحيطة وتتبعها في الوقت الفعلي.', 'Recognized traffic lights and responded to their signals.': 'التعرف على إشارات المرور والاستجابة لها.', 'Followed lanes and made basic autonomous navigation decisions.': 'اتباع المسارات واتخاذ قرارات تنقل ذاتية أساسية.', 'After-Sales Service Management Web App': 'تطبيق ويب لإدارة خدمات ما بعد البيع', 'Built a role-based after-sales portal where customers submit product complaints and follow repair interventions, while administrators manage the product catalog and service workflow.': 'أنشأت بوابة لخدمات ما بعد البيع بصلاحيات متعددة، يرسل فيها العملاء شكاوى المنتجات ويتابعون الإصلاحات، بينما يدير المسؤولون كتالوج المنتجات وسير الخدمة.', 'Client area for submitting complaints and viewing warranty status, repair interventions, and spare parts used.': 'مساحة للعملاء لإرسال الشكاوى وعرض حالة الضمان والإصلاحات وقطع الغيار المستخدمة.', 'Admin tools for managing catalog articles, complaints, interventions, and spare parts.': 'أدوات للمسؤولين لإدارة المنتجات والشكاوى والإصلاحات وقطع الغيار.', 'Warranty-aware service costs, including labor and replacement parts.': 'حساب تكاليف الخدمة وفق الضمان، بما فيها أجور العمل وقطع الغيار.', 'Key responsibilities': 'المسؤوليات الرئيسية', 'Technologies': 'التقنيات', 'Explore project': 'استكشف المشروع', 'View source on GitHub': 'عرض المصدر على GitHub',
    'Always': 'دائماً', 'building forward.': 'نواصل التقدم.', 'A foundation in software.': 'أساس متين في البرمجيات.', 'An ongoing commitment to learning.': 'التزام مستمر بالتعلم.', 'In Progress': 'قيد الدراسة', 'Completed': 'مكتمل', 'Study areas': 'مجالات الدراسة', 'Available for full-time daytime work': 'متاح للعمل بدوام كامل نهاراً', 'Engineering Cycle in Computer Science': 'مرحلة الهندسة في علوم الحاسوب', 'Graduate in Computer Science and Information Systems.': 'خريج علوم الحاسوب ونظم المعلومات.', 'Bachelor’s Degree in Computer Science and Information Systems': 'إجازة في علوم الحاسوب ونظم المعلومات', 'Baccalaureate in Technical Sciences': 'البكالوريا في العلوم التقنية', 'Technical Sciences baccalaureate.': 'بكالوريا في العلوم التقنية.', 'Evening classes': 'دروس مسائية', 'Computer Science': 'علوم الحاسوب', 'Information Systems': 'نظم المعلومات', 'Technical Sciences': 'العلوم التقنية',
    'LET’S CONNECT': 'لنتواصل', 'Let’s build': 'لنبنِ', 'something': 'شيئاً', 'great.': 'مميزاً.', 'I’m open to opportunities in full-stack development, embedded systems, IoT, mobile development, and software testing.': 'أنا منفتح على فرص في تطوير Full-Stack والأنظمة المضمنة وإنترنت الأشياء وتطبيقات الهاتف واختبار البرمجيات.', 'Have a role or a project in mind?': 'هل لديك وظيفة أو مشروع في ذهنك؟', 'I’d love to hear about it.': 'يسعدني أن أسمع عنه.', 'Available for full-time daytime work · Evening studies': 'متاح للعمل بدوام كامل نهاراً · الدراسة مساءً', 'Start a conversation': 'ابدأ محادثة', 'SAY HELLO': 'مرحباً', 'Name': 'الاسم', 'Email': 'البريد الإلكتروني', 'Subject': 'الموضوع', 'Message': 'الرسالة', 'Your name': 'اسمك', 'An opportunity, a project, an introduction…': 'فرصة أو مشروع أو تعارف…', 'Tell me a little about what you have in mind.': 'أخبرني قليلاً عما تفكر فيه.', 'Leave this empty': 'اترك هذا الحقل فارغاً', 'Sending…': 'جارٍ الإرسال…', 'Copy message': 'نسخ الرسالة', 'Send message': 'إرسال الرسالة', 'Open email draft': 'فتح مسودة البريد', 'This only copies a message. It will not be sent; use the listed contact details to send it.': 'سيتم نسخ الرسالة فقط ولن تُرسل. استخدم بيانات الاتصال لإرسالها.', 'Your details are used to respond to your inquiry. This form uses an external message delivery service.': 'ستُستخدم بياناتك للرد على استفسارك. يستخدم النموذج خدمة خارجية لإرسال الرسائل.', 'This opens your email app with a draft for you to review and send.': 'سيفتح تطبيق البريد مسودة لتراجعها وترسلها.', 'Please complete each field before continuing.': 'يرجى إكمال جميع الحقول قبل المتابعة.', 'Message copied. It has not been sent. Use the contact details on this page to send it.': 'نُسخت الرسالة ولم تُرسل. استخدم بيانات الاتصال في هذه الصفحة لإرسالها.', 'Select and copy your message below. It has not been sent.': 'حدد رسالتك أدناه وانسخها. لم يتم إرسالها.', 'Your email app has been requested. Review and send the draft there. Nothing is sent by this website.': 'سيُفتح تطبيق البريد. راجع المسودة وأرسلها بنفسك. لم يرسل هذا الموقع أي شيء.', 'Thank you. Your message has been submitted successfully.': 'شكراً لك، تم إرسال رسالتك بنجاح.', 'Your message could not be sent. Please try again': 'تعذر إرسال رسالتك. يرجى المحاولة مجدداً', ' or use the email link.': ' أو استخدم رابط البريد الإلكتروني.', ' later.': ' لاحقاً.', 'Email details coming soon': 'ستتوفر بيانات البريد قريباً', 'Your message': 'رسالتك',
    'Back to top': 'العودة إلى الأعلى', 'All rights reserved.': 'جميع الحقوق محفوظة.', 'Thoughtfully built. Always evolving.': 'صُمم بعناية ويتطور باستمرار.',
    'System flows and architecture': 'تدفقات النظام وبنيته', 'Visual guides to Wi-Fi setup, controller synchronization, and firmware updates.': 'رسوم توضيحية لإعداد Wi-Fi ومزامنة وحدة التحكم وتحديث البرنامج المضمن.', 'Product views': 'واجهات المنتج', 'Controller screen, mobile schedule, and system overview.': 'شاشة وحدة التحكم وجدول الهاتف ونظرة عامة على النظام.', 'Hide mobile app screen album': 'إخفاء صور تطبيق الهاتف', 'Browse mobile app screen album': 'استعراض صور تطبيق الهاتف', 'screens': 'شاشات', 'BlueBox mobile app screens': 'شاشات تطبيق BlueBox للهاتف', 'Sign-in, account setup, password recovery, valve onboarding, and irrigation scheduling.': 'تسجيل الدخول وإنشاء الحساب واستعادة كلمة المرور وإضافة الصمامات وجدولة الري.', 'Hide embedded screen album': 'إخفاء صور النظام المضمن', 'Browse embedded screen album': 'استعراض صور النظام المضمن', 'Embedded controller screens': 'شاشات وحدة التحكم المضمنة', 'Select any screen to view it larger. Use the arrow keys or buttons to browse.': 'اختر أي شاشة لعرضها بحجم أكبر. استخدم الأسهم أو الأزرار للتنقل.', 'PROJECT GALLERY': 'معرض المشروع', 'Close image viewer': 'إغلاق عارض الصور', 'Previous screenshot': 'الصورة السابقة', 'Next screenshot': 'الصورة التالية', 'Use left/right arrow keys to browse | Esc to close': 'استخدم السهمين الأيمن والأيسر للتنقل | Esc للإغلاق', 'Image unavailable': 'الصورة غير متاحة', 'Controller & valves': 'وحدة التحكم والصمامات', 'Mobile application': 'تطبيق الهاتف', 'Web dashboard': 'لوحة الويب', 'Product image coming soon': 'صورة المنتج قريباً', 'application screens': 'شاشات التطبيق', 'Browse selected screens from the': 'استعرض مجموعة مختارة من شاشات', 'Open screenshot:': 'افتح الصورة:', 'Close navigation': 'إغلاق القائمة', 'Open navigation': 'فتح القائمة',
    'Computer hardware': 'أجهزة الحاسوب', 'Installation': 'التركيب', 'Configuration': 'التهيئة', 'Troubleshooting': 'استكشاف الأخطاء', 'Frontend development': 'تطوير الواجهات الأمامية', 'Web UI': 'واجهة الويب', 'Robotics project': 'مشروع روبوتات', 'Full-stack development': 'تطوير Full-Stack', 'Full-stack & IoT internship': 'تدريب Full-Stack وإنترنت الأشياء', 'Full-stack internship': 'تدريب Full-Stack', 'Computer vision': 'الرؤية الحاسوبية', 'Object detection': 'اكتشاف الأجسام', 'Traffic-light recognition': 'التعرف على إشارات المرور', 'Lane following': 'اتباع المسار', 'Autonomous navigation': 'التنقل الذاتي', 'Vehicle diagnostics': 'تشخيص المركبات', 'Sensor data': 'بيانات المستشعرات', 'Data visualization': 'عرض البيانات',
  },
};

const supplemental = {
  fr: {
    'Sfax, Tunisia': 'Sfax, Tunisie',
    'People can set up the controller, manage irrigation remotely, and still use its local screen in the field.': 'L’utilisateur peut configurer le contrôleur, gérer l’irrigation à distance et continuer à utiliser son écran local sur le terrain.',
    'During setup, the mobile app sends Wi-Fi credentials to the controller through a local REST/JSON flow. The React and Flutter applications use REST APIs with Spring Boot services, while the ESP32-S3 controller synchronizes status, programs, and commands over MQTT. Firebase Cloud Messaging delivers user alerts, and the TFT remains available for local operation.': 'Lors de la configuration, l’application mobile transmet les identifiants Wi-Fi au contrôleur via un échange REST/JSON local. Les applications React et Flutter utilisent les API REST des services Spring Boot, tandis que le contrôleur ESP32-S3 synchronise les états, programmes et commandes via MQTT. Firebase Cloud Messaging envoie les alertes et l’écran TFT reste disponible pour le contrôle local.',
    'Backend APIs & device management': 'API backend et gestion des appareils', 'React web dashboard': 'Tableau de bord web React', 'Flutter mobile application': 'Application mobile Flutter', 'Remote valve control': 'Contrôle à distance des vannes', 'Irrigation scheduling': 'Programmation de l’irrigation', 'Controller onboarding': 'Configuration du contrôleur', 'Local TFT controller interface': 'Interface locale du contrôleur TFT', 'Real-time controller status': 'État du contrôleur en temps réel', 'HTTPS firmware updates (OTA)': 'Mises à jour firmware HTTPS (OTA)', 'Firebase push notifications': 'Notifications push Firebase', 'Sensor and pressure monitoring': 'Surveillance des capteurs et de la pression', 'API, integration, and system testing': 'Tests API, intégration et système',
    'Commercial Management Web Application': 'Application web de gestion commerciale', 'Customer storefront · Orders · Quotes · Admin portal': 'Boutique client · Commandes · Devis · Portail admin',
    'Product, customer, order, and quote workflows relied on disconnected or manual processes, making information harder to find and follow for both customers and administrators.': 'La gestion des produits, clients, commandes et devis reposait sur des processus manuels ou dispersés, compliquant le suivi pour les clients comme pour les administrateurs.',
    'Built a responsive customer storefront and a protected admin workspace over a service-based backend, bringing the product catalog, orders, quotes, and customer records into one application.': 'Création d’une boutique client adaptative et d’un espace d’administration sécurisé sur un backend composé de services, réunissant le catalogue, les commandes, les devis et les dossiers clients.',
    'I developed the customer and administration workflows.': 'J’ai développé les parcours client et administration.',
    'Implemented the product storefront, cart, delivery checkout, and order submission. The order flow produces a quote that customers can look up by email and download as a PDF.': 'Mise en place de la boutique, du panier, de la livraison et de la validation des commandes. Le parcours génère un devis que le client peut rechercher par e-mail et télécharger en PDF.',
    'Built administration screens for product management, customer records, order tracking, and quote review. Administrators can update the catalog, follow order status, and validate or respond to quotes.': 'Création des écrans d’administration pour les produits, les dossiers clients, le suivi des commandes et la revue des devis. Les administrateurs peuvent actualiser le catalogue, suivre les commandes et valider ou commenter les devis.',
    'Connected the React interface to Spring Boot services through Spring Cloud routing and an API Gateway, with Spring Data JPA and MySQL for persistence.': 'Connexion de l’interface React aux services Spring Boot via Spring Cloud et une passerelle API, avec Spring Data JPA et MySQL pour la persistance.',
    'Tested individual REST services with Postman and checked frontend/backend integration. Organized development with Kanban and documented the design with MVC concepts and UML use-case, sequence, and class diagrams.': 'Test des services REST avec Postman et vérification de l’intégration frontend/backend. Organisation avec Kanban et documentation de la conception à l’aide des concepts MVC et de diagrammes UML de cas d’utilisation, séquence et classes.',
    'Customer storefront': 'Boutique client', 'Administration portal': 'Portail d’administration', 'Customer and admin workflows over shared services.': 'Parcours client et admin sur des services partagés.', 'APPLICATION ARCHITECTURE': 'ARCHITECTURE DE L’APPLICATION', 'METHOD & DESIGN': 'MÉTHODE ET CONCEPTION', 'TOOLS & TECHNOLOGIES': 'OUTILS ET TECHNOLOGIES',
    'Customers browse the product catalog, add items to a cart, enter delivery details, submit an order, and retrieve generated quotes.': 'Les clients consultent le catalogue, ajoutent des articles au panier, saisissent leurs informations de livraison, passent commande et récupèrent les devis générés.',
    'Administrators use a sign-in area and dashboard to manage products and customers and follow orders and quotes.': 'Les administrateurs disposent d’un espace de connexion et d’un tableau de bord pour gérer les produits et les clients, et suivre commandes et devis.',
    'The backend is organized as MVC microservices, with an API Gateway routing requests and Spring Cloud supporting service configuration and discovery.': 'Le backend est organisé en microservices MVC. Une passerelle API achemine les requêtes et Spring Cloud prend en charge la configuration et la découverte des services.',
    'Relational records cover customers, products, orders, and quotes. REST endpoints and frontend/backend integration were checked during development.': 'La base relationnelle gère les clients, produits, commandes et devis. Les API REST et l’intégration frontend/backend ont été vérifiées pendant le développement.',
    'Work was organized with Kanban. The report documents MVC concepts and UML use-case, sequence, and class diagrams.': 'Le travail a été organisé avec Kanban. Le rapport présente les concepts MVC et les diagrammes UML de cas d’utilisation, de séquence et de classes.',
    'Java · Spring Boot · Spring Cloud': 'Java · Spring Boot · Spring Cloud', 'React · Protected access': 'React · accès protégé', 'Spring Data JPA · MySQL · Postman': 'Spring Data JPA · MySQL · Postman',
    'Feb 2026 — Jun 2026': 'Févr. 2026 — juin 2026', 'Jun 2025 — Aug 2025': 'Juin 2025 — août 2025', 'Aug 2024 — Sep 2024': 'Août 2024 — sept. 2024', 'Jun 2024 — Jul 2024': 'Juin 2024 — juil. 2024', 'Jan 2026 — present': 'Janv. 2026 — aujourd’hui', 'Jan 2025 — Dec 2025': 'Janv. 2025 — déc. 2025', 'May 2024 — Dec 2024': 'Mai 2024 — déc. 2024', '2019 — present': '2019 — aujourd’hui', '2026 — present': '2026 — aujourd’hui', '2023 — 2026': '2023 — 2026',
    'Institut International de Technologie (IIT) · Evening classes': 'Institut International de Technologie (IIT) · cours du soir', 'Lycée Ibn Rachik · Sfax': 'Lycée Ibn Rachik · Sfax',
    'application screens': 'écrans de l’application', 'Browse selected screens from the': 'Parcourir une sélection d’écrans de', 'application.': 'application.', 'product images': 'images du produit', 'Controller screen, mobile schedule, and system overview.': 'Écran du contrôleur, programme mobile et vue d’ensemble du système.',
    'BlueBox irrigation test installation with connected pipes, valves, pressure filter, and controller hardware': 'Installation de test BlueBox avec tuyaux, vannes, filtre de pression et matériel de contrôle connectés', 'Real irrigation hardware used to integrate and validate the BlueBox controller with the valve and pressure system.': 'Matériel d’irrigation réel utilisé pour intégrer et valider le contrôleur BlueBox avec le système de vannes et de pression.', 'BlueBox controller display showing the irrigation schedule, valve states, pump status, and pressure fields': 'Écran du contrôleur BlueBox affichant le programme d’irrigation, les vannes, la pompe et la pression', 'BlueBox mobile app showing an irrigation schedule with weekdays, months, and valve durations': 'Application mobile BlueBox avec les jours, mois et durées d’irrigation des vannes', 'BlueBox system overview connecting the mobile app, irrigation controller, and backend': 'Vue d’ensemble BlueBox reliant l’application mobile, le contrôleur d’irrigation et le backend',
    'Currently continuing my studies in an evening program.': 'Je poursuis actuellement mes études dans un programme du soir.', 'Academic project': 'Projet académique', 'Login and vehicle comparison': 'Connexion et comparaison des véhicules', 'Vehicle profile': 'Profil du véhicule', 'Live dashboard': 'Tableau de bord en direct', 'Vehicle and fuel analysis': 'Analyse du véhicule et du carburant', 'Sensor status': 'État des capteurs', 'The team and the finished prototype': 'L’équipe et le prototype final',
    'Customer storefront · product catalog': 'Boutique client · catalogue produits', 'Customer storefront · cart and checkout': 'Boutique client · panier et commande', 'Customer storefront · quote lookup': 'Boutique client · recherche de devis', 'Administration · sign in': 'Administration · connexion', 'Administration · dashboard': 'Administration · tableau de bord', 'Administration · product management': 'Administration · gestion des produits', 'Administration · order management': 'Administration · gestion des commandes', 'Administration · quote management': 'Administration · gestion des devis', 'Administration · client management': 'Administration · gestion des clients',
    'Application screens': 'Écrans de l’application', 'Browse selected application screens for': 'Parcourir une sélection d’écrans de l’application',
  },
  ar: {
    'Sfax, Tunisia': 'صفاقس، تونس', 'People can set up the controller, manage irrigation remotely, and still use its local screen in the field.': 'يمكن للمستخدم إعداد وحدة التحكم وإدارة الري عن بُعد واستخدام شاشتها المحلية في الحقل.',
    'During setup, the mobile app sends Wi-Fi credentials to the controller through a local REST/JSON flow. The React and Flutter applications use REST APIs with Spring Boot services, while the ESP32-S3 controller synchronizes status, programs, and commands over MQTT. Firebase Cloud Messaging delivers user alerts, and the TFT remains available for local operation.': 'أثناء الإعداد، يرسل تطبيق الهاتف بيانات Wi-Fi إلى وحدة التحكم عبر اتصال REST/JSON محلي. تستخدم تطبيقات React وFlutter واجهات REST مع خدمات Spring Boot، بينما تزامن وحدة ESP32-S3 الحالة والبرامج والأوامر عبر MQTT. ترسل Firebase Cloud Messaging التنبيهات، وتبقى شاشة TFT متاحة للتشغيل المحلي.',
    'Backend APIs & device management': 'واجهات الخادم وإدارة الأجهزة', 'React web dashboard': 'لوحة ويب باستخدام React', 'Flutter mobile application': 'تطبيق هاتف باستخدام Flutter', 'Remote valve control': 'التحكم عن بُعد بالصمامات', 'Irrigation scheduling': 'جدولة الري', 'Controller onboarding': 'إعداد وحدة التحكم', 'Local TFT controller interface': 'واجهة TFT المحلية لوحدة التحكم', 'Real-time controller status': 'حالة وحدة التحكم مباشرة', 'HTTPS firmware updates (OTA)': 'تحديثات البرنامج OTA عبر HTTPS', 'Firebase push notifications': 'إشعارات Firebase', 'Sensor and pressure monitoring': 'مراقبة المستشعرات والضغط', 'API, integration, and system testing': 'اختبارات API والتكامل والنظام',
    'Commercial Management Web Application': 'تطبيق ويب للإدارة التجارية', 'Customer storefront · Orders · Quotes · Admin portal': 'متجر العملاء · الطلبات · عروض الأسعار · بوابة الإدارة',
    'Product, customer, order, and quote workflows relied on disconnected or manual processes, making information harder to find and follow for both customers and administrators.': 'اعتمدت إدارة المنتجات والعملاء والطلبات وعروض الأسعار على إجراءات يدوية ومتفرقة، مما صعّب العثور على المعلومات ومتابعتها للعملاء والإداريين.',
    'Built a responsive customer storefront and a protected admin workspace over a service-based backend, bringing the product catalog, orders, quotes, and customer records into one application.': 'أنشأت متجراً متجاوباً للعملاء ومساحة إدارة محمية فوق خادم قائم على الخدمات، وجمعت كتالوج المنتجات والطلبات وعروض الأسعار وسجلات العملاء في تطبيق واحد.',
    'I developed the customer and administration workflows.': 'طورت مسارات العمل الخاصة بالعملاء والإدارة.',
    'Implemented the product storefront, cart, delivery checkout, and order submission. The order flow produces a quote that customers can look up by email and download as a PDF.': 'نفذت متجر المنتجات وسلة التسوق وإدخال بيانات التوصيل وإرسال الطلب. وينشئ الطلب عرض سعر يستطيع العميل البحث عنه بالبريد الإلكتروني وتنزيله بصيغة PDF.',
    'Built administration screens for product management, customer records, order tracking, and quote review. Administrators can update the catalog, follow order status, and validate or respond to quotes.': 'أنشأت شاشات إدارية لإدارة المنتجات وسجلات العملاء ومتابعة الطلبات ومراجعة عروض الأسعار. ويمكن للإداريين تحديث الكتالوج ومتابعة حالة الطلبات واعتماد عروض الأسعار أو الرد عليها.',
    'Connected the React interface to Spring Boot services through Spring Cloud routing and an API Gateway, with Spring Data JPA and MySQL for persistence.': 'ربطت واجهة React بخدمات Spring Boot عبر توجيه Spring Cloud وبوابة API، واستخدمت Spring Data JPA وMySQL لحفظ البيانات.',
    'Tested individual REST services with Postman and checked frontend/backend integration. Organized development with Kanban and documented the design with MVC concepts and UML use-case, sequence, and class diagrams.': 'اختبرت خدمات REST باستخدام Postman وتحققت من تكامل الواجهات الأمامية والخلفية. نظمت التطوير باستخدام Kanban ووثقت التصميم بمفاهيم MVC ومخططات UML لحالات الاستخدام والتسلسل والفئات.',
    'Customer storefront': 'متجر العملاء', 'Administration portal': 'بوابة الإدارة', 'Customer and admin workflows over shared services.': 'مسارات العملاء والإدارة فوق خدمات مشتركة.', 'APPLICATION ARCHITECTURE': 'بنية التطبيق', 'METHOD & DESIGN': 'المنهجية والتصميم', 'TOOLS & TECHNOLOGIES': 'الأدوات والتقنيات',
    'Customers browse the product catalog, add items to a cart, enter delivery details, submit an order, and retrieve generated quotes.': 'يتصفح العملاء كتالوج المنتجات ويضيفون العناصر إلى السلة ويدخلون بيانات التوصيل ويرسلون الطلب ويحصلون على عروض الأسعار.', 'Administrators use a sign-in area and dashboard to manage products and customers and follow orders and quotes.': 'يستخدم الإداريون صفحة الدخول ولوحة التحكم لإدارة المنتجات والعملاء ومتابعة الطلبات وعروض الأسعار.', 'The backend is organized as MVC microservices, with an API Gateway routing requests and Spring Cloud supporting service configuration and discovery.': 'ينظم الخادم كخدمات مصغرة وفق MVC، وتوجه بوابة API الطلبات بينما يدعم Spring Cloud إعداد الخدمات واكتشافها.', 'Relational records cover customers, products, orders, and quotes. REST endpoints and frontend/backend integration were checked during development.': 'تضم قاعدة البيانات العلائقية سجلات العملاء والمنتجات والطلبات وعروض الأسعار. وتم التحقق من نقاط REST وتكامل الواجهات خلال التطوير.', 'Work was organized with Kanban. The report documents MVC concepts and UML use-case, sequence, and class diagrams.': 'نُظم العمل باستخدام Kanban. ويوثق التقرير مفاهيم MVC ومخططات UML لحالات الاستخدام والتسلسل والفئات.',
    'Java · Spring Boot · Spring Cloud': 'Java · Spring Boot · Spring Cloud', 'React · Protected access': 'React · دخول محمي', 'Spring Data JPA · MySQL · Postman': 'Spring Data JPA · MySQL · Postman',
    'Feb 2026 — Jun 2026': 'فبراير 2026 — يونيو 2026', 'Jun 2025 — Aug 2025': 'يونيو 2025 — أغسطس 2025', 'Aug 2024 — Sep 2024': 'أغسطس 2024 — سبتمبر 2024', 'Jun 2024 — Jul 2024': 'يونيو 2024 — يوليو 2024', 'Jan 2026 — present': 'يناير 2026 — الآن', 'Jan 2025 — Dec 2025': 'يناير 2025 — ديسمبر 2025', 'May 2024 — Dec 2024': 'مايو 2024 — ديسمبر 2024', '2019 — present': '2019 — الآن', '2026 — present': '2026 — الآن', '2023 — 2026': '2023 — 2026',
    'Institut International de Technologie (IIT) · Evening classes': 'المعهد الدولي للتكنولوجيا (IIT) · دروس مسائية', 'Lycée Ibn Rachik · Sfax': 'معهد ابن رشيق · صفاقس',
    'application screens': 'شاشات التطبيق', 'Browse selected screens from the': 'استعرض مجموعة مختارة من شاشات', 'application.': 'التطبيق.', 'product images': 'صور المنتج', 'Controller screen, mobile schedule, and system overview.': 'شاشة وحدة التحكم وجدول الهاتف ونظرة عامة على النظام.',
    'BlueBox irrigation test installation with connected pipes, valves, pressure filter, and controller hardware': 'منظومة اختبار ري BlueBox مع أنابيب وصمامات ومرشح ضغط ووحدة تحكم متصلة', 'Real irrigation hardware used to integrate and validate the BlueBox controller with the valve and pressure system.': 'أجهزة ري فعلية استُخدمت لدمج وحدة تحكم BlueBox والتحقق منها مع نظام الصمامات والضغط.', 'BlueBox controller display showing the irrigation schedule, valve states, pump status, and pressure fields': 'شاشة وحدة تحكم BlueBox تعرض جدول الري وحالة الصمامات والمضخة والضغط', 'BlueBox mobile app showing an irrigation schedule with weekdays, months, and valve durations': 'تطبيق BlueBox يعرض جدول الري وأيام الأسبوع والأشهر ومدد تشغيل الصمامات', 'BlueBox system overview connecting the mobile app, irrigation controller, and backend': 'مخطط BlueBox يربط تطبيق الهاتف ووحدة تحكم الري والخادم',
    'Currently continuing my studies in an evening program.': 'أواصل دراستي حالياً ضمن برنامج مسائي.', 'Academic project': 'مشروع أكاديمي', 'Login and vehicle comparison': 'تسجيل الدخول ومقارنة المركبات', 'Vehicle profile': 'ملف المركبة', 'Live dashboard': 'لوحة متابعة مباشرة', 'Vehicle and fuel analysis': 'تحليل المركبة والوقود', 'Sensor status': 'حالة المستشعرات', 'The team and the finished prototype': 'الفريق والنموذج الأولي النهائي',
    'Customer storefront · product catalog': 'متجر العملاء · كتالوج المنتجات', 'Customer storefront · cart and checkout': 'متجر العملاء · السلة وإتمام الطلب', 'Customer storefront · quote lookup': 'متجر العملاء · البحث عن عرض سعر', 'Administration · sign in': 'الإدارة · تسجيل الدخول', 'Administration · dashboard': 'الإدارة · لوحة التحكم', 'Administration · product management': 'الإدارة · إدارة المنتجات', 'Administration · order management': 'الإدارة · إدارة الطلبات', 'Administration · quote management': 'الإدارة · إدارة عروض الأسعار', 'Administration · client management': 'الإدارة · إدارة العملاء',
    'Application screens': 'شاشات التطبيق', 'Browse selected application screens for': 'استعرض مجموعة مختارة من شاشات التطبيق',
  },
};

const galleryTranslations = {
  fr: {
    'Mobile app · Sign in': 'Application mobile · Connexion', 'Mobile app · Create an account': 'Application mobile · Créer un compte', 'Mobile app · Password recovery': 'Application mobile · Récupération du mot de passe', 'Mobile app · Add a valve with QR': 'Application mobile · Ajouter une vanne par QR',
    'Controller modes · overview': 'Modes du contrôleur · aperçu', 'Home screen · active irrigation': 'Écran d’accueil · irrigation active', 'Controller · network unavailable': 'Contrôleur · réseau indisponible', 'Valve state display': 'Affichage de l’état des vannes', 'Remote valve state': 'État des vannes à distance', 'Manual control · valve states': 'Commande manuelle · états des vannes', 'Program countdown and readings': 'Compte à rebours du programme et mesures', 'Controller settings · overview': 'Paramètres du contrôleur · aperçu', 'Pressure alerts': 'Alertes de pression', 'Early controller screen': 'Première interface du contrôleur', 'Valve page · four zones': 'Page des vannes · quatre zones', 'Valve page · eight zones': 'Page des vannes · huit zones', 'Program overview': 'Aperçu du programme', 'Manual valve control layouts': 'Interfaces de commande manuelle des vannes',
    'Onboarding · waiting for connection': 'Configuration · en attente de connexion', 'Onboarding · user connected': 'Configuration · utilisateur connecté', 'Onboarding · internet check': 'Configuration · vérification Internet', 'Onboarding · connected successfully': 'Configuration · connexion réussie', 'Program timing and valve durations': 'Horaires du programme et durées des vannes', 'Settings menu': 'Menu des paramètres', 'Date settings': 'Réglage de la date', 'Confirm onboarding reset': 'Confirmer la réinitialisation de la configuration', 'Program schedule · eight valves': 'Programme d’irrigation · huit vannes', 'Controller status · four zones': 'État du contrôleur · quatre zones', 'Controller status · eight zones': 'État du contrôleur · huit zones', 'Program schedule · choose days': 'Programme d’irrigation · choisir les jours', 'Program schedule · choose months': 'Programme d’irrigation · choisir les mois', 'Program schedule · month summary': 'Programme d’irrigation · récapitulatif des mois', 'Controller program status': 'État du programme du contrôleur', 'Program schedule · day settings': 'Programme d’irrigation · réglage des jours', 'Time settings': 'Réglage de l’heure', 'Program schedule · zone durations': 'Programme d’irrigation · durées par zone', 'Wi-Fi setup · available networks': 'Configuration Wi-Fi · réseaux disponibles', 'Wi-Fi setup · enter credentials': 'Configuration Wi-Fi · saisir les identifiants', 'Wi-Fi setup · number keyboard': 'Configuration Wi-Fi · clavier numérique', 'Wi-Fi setup · symbols keyboard': 'Configuration Wi-Fi · clavier des symboles', 'Add a valve · confirmation': 'Ajouter une vanne · confirmation', 'Add a valve · in progress': 'Ajouter une vanne · en cours', 'Stop irrigation · controller dialog': 'Arrêter l’irrigation · dialogue du contrôleur', 'Stop irrigation · confirmation': 'Arrêt de l’irrigation · confirmation', 'Controller · sleep state': 'Contrôleur · mode veille', 'Settings menu · controller': 'Menu des paramètres · contrôleur', 'Pressure settings · controller': 'Paramètres de pression · contrôleur',
  },
  ar: {
    'Mobile app · Sign in': 'تطبيق الهاتف · تسجيل الدخول', 'Mobile app · Create an account': 'تطبيق الهاتف · إنشاء حساب', 'Mobile app · Password recovery': 'تطبيق الهاتف · استعادة كلمة المرور', 'Mobile app · Add a valve with QR': 'تطبيق الهاتف · إضافة صمام عبر QR',
    'Controller modes · overview': 'أوضاع وحدة التحكم · نظرة عامة', 'Home screen · active irrigation': 'الشاشة الرئيسية · الري نشط', 'Controller · network unavailable': 'وحدة التحكم · الشبكة غير متاحة', 'Valve state display': 'عرض حالة الصمامات', 'Remote valve state': 'حالة الصمام عن بُعد', 'Manual control · valve states': 'التحكم اليدوي · حالات الصمامات', 'Program countdown and readings': 'العد التنازلي للبرنامج والقراءات', 'Controller settings · overview': 'إعدادات وحدة التحكم · نظرة عامة', 'Pressure alerts': 'تنبيهات الضغط', 'Early controller screen': 'واجهة أولية لوحدة التحكم', 'Valve page · four zones': 'صفحة الصمامات · أربع مناطق', 'Valve page · eight zones': 'صفحة الصمامات · ثماني مناطق', 'Program overview': 'نظرة عامة على البرنامج', 'Manual valve control layouts': 'واجهات التحكم اليدوي بالصمامات',
    'Onboarding · waiting for connection': 'الإعداد · بانتظار الاتصال', 'Onboarding · user connected': 'الإعداد · تم اتصال المستخدم', 'Onboarding · internet check': 'الإعداد · التحقق من الإنترنت', 'Onboarding · connected successfully': 'الإعداد · تم الاتصال بنجاح', 'Program timing and valve durations': 'توقيت البرنامج ومدد الصمامات', 'Settings menu': 'قائمة الإعدادات', 'Date settings': 'إعداد التاريخ', 'Confirm onboarding reset': 'تأكيد إعادة ضبط الإعداد', 'Program schedule · eight valves': 'جدول البرنامج · ثمانية صمامات', 'Controller status · four zones': 'حالة وحدة التحكم · أربع مناطق', 'Controller status · eight zones': 'حالة وحدة التحكم · ثماني مناطق', 'Program schedule · choose days': 'جدول البرنامج · اختيار الأيام', 'Program schedule · choose months': 'جدول البرنامج · اختيار الأشهر', 'Program schedule · month summary': 'جدول البرنامج · ملخص الأشهر', 'Controller program status': 'حالة برنامج وحدة التحكم', 'Program schedule · day settings': 'جدول البرنامج · إعداد الأيام', 'Time settings': 'إعداد الوقت', 'Program schedule · zone durations': 'جدول البرنامج · مدد المناطق', 'Wi-Fi setup · available networks': 'إعداد Wi-Fi · الشبكات المتاحة', 'Wi-Fi setup · enter credentials': 'إعداد Wi-Fi · إدخال بيانات الاتصال', 'Wi-Fi setup · number keyboard': 'إعداد Wi-Fi · لوحة أرقام', 'Wi-Fi setup · symbols keyboard': 'إعداد Wi-Fi · لوحة رموز', 'Add a valve · confirmation': 'إضافة صمام · تأكيد', 'Add a valve · in progress': 'إضافة صمام · جارٍ التنفيذ', 'Stop irrigation · controller dialog': 'إيقاف الري · حوار وحدة التحكم', 'Stop irrigation · confirmation': 'إيقاف الري · تأكيد', 'Controller · sleep state': 'وحدة التحكم · وضع السكون', 'Settings menu · controller': 'قائمة الإعدادات · وحدة التحكم', 'Pressure settings · controller': 'إعدادات الضغط · وحدة التحكم',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try {
      const saved = window.localStorage.getItem('portfolio-language');
      return ['en', 'fr', 'ar'].includes(saved) ? saved : 'en';
    } catch { return 'en'; }
  });

  useEffect(() => {
    const root = document.documentElement;
    root.lang = language;
    root.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.title = translations[language]?.['Mohamed Yahya Sellami | Full-Stack, IoT & Software Testing'] || 'Mohamed Yahya Sellami | Full-Stack, IoT & Software Testing';
    try { window.localStorage.setItem('portfolio-language', language); } catch { /* Language selection remains active for this tab. */ }
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (text) => galleryTranslations[language]?.[text] || supplemental[language]?.[text] || translations[language]?.[text] || text,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
}
